
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.imageio.ImageIO;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Control2D.java
 *
 * Created on Nov 18, 2010, 9:35:00 PM
 */

/**
 *
 * @author meng
 */
public class Control2D extends javax.swing.JPanel {
    New2D dd;
    TwoDJFrame ff;

    /** Creates new form Control2D */
    public Control2D(New2D dd, TwoDJFrame ff) {
        this.dd = dd;
        this.ff = ff;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewGroup = new javax.swing.ButtonGroup();
        side = new javax.swing.JRadioButton();
        top = new javax.swing.JRadioButton();
        backbone = new javax.swing.JCheckBox();
        out = new javax.swing.JCheckBox();
        in = new javax.swing.JCheckBox();
        electrical = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        zoomBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        zspacingBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showPartners = new javax.swing.JTextPane();
        save = new javax.swing.JButton();
        print = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(200, 768));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 768));

        viewGroup.add(side);
        side.setSelected(true);
        side.setText("side view");
        side.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideActionPerformed(evt);
            }
        });

        viewGroup.add(top);
        top.setText("top view");
        top.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topActionPerformed(evt);
            }
        });

        backbone.setSelected(true);
        backbone.setText("backbone");
        backbone.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                backboneItemStateChanged(evt);
            }
        });

        out.setSelected(true);
        out.setText("chemical out");
        out.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                outItemStateChanged(evt);
            }
        });

        in.setSelected(true);
        in.setText("chemical in");
        in.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inItemStateChanged(evt);
            }
        });

        electrical.setSelected(true);
        electrical.setText("electrical");
        electrical.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                electricalItemStateChanged(evt);
            }
        });

        jLabel1.setText("zoom:");

        zoomBox.setText("1.00");
        zoomBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zoomBoxKeyPressed(evt);
            }
        });

        jLabel2.setText("z-spacing:");

        zspacingBox.setText("1.00");
        zspacingBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zspacingBoxKeyPressed(evt);
            }
        });

        jLabel3.setText("Input partners to show:");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(120, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(120, 100));

        showPartners.setMaximumSize(new java.awt.Dimension(20, 100));
        showPartners.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showPartnersKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(showPartners);

        save.setText("save as Image");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        print.setText("print diagram");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electrical)
                    .addComponent(in)
                    .addComponent(out)
                    .addComponent(backbone)
                    .addComponent(top)
                    .addComponent(side)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(31, 31, 31)
                            .addComponent(zoomBox))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(zspacingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(print, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(side)
                .addGap(18, 18, 18)
                .addComponent(top)
                .addGap(18, 18, 18)
                .addComponent(backbone)
                .addGap(18, 18, 18)
                .addComponent(out)
                .addGap(18, 18, 18)
                .addComponent(in)
                .addGap(18, 18, 18)
                .addComponent(electrical)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(zoomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(zspacingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(save)
                .addGap(18, 18, 18)
                .addComponent(print)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideActionPerformed
        dd.dtype = "Y_Z";
        dd.repaint();
    }//GEN-LAST:event_sideActionPerformed

    private void topActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topActionPerformed
        dd.dtype = "X_Z";
        dd.repaint();
    }//GEN-LAST:event_topActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        savePNG(ff);
        savePNG(dd);
    }//GEN-LAST:event_saveActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       // PrintUtilities.printComponent(dd);
    }//GEN-LAST:event_printActionPerformed

    private void zspacingBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zspacingBoxKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        dd.spacing = Float.parseFloat(zspacingBox.getText());
        dd.repaint();
        }
    }//GEN-LAST:event_zspacingBoxKeyPressed

    private void zoomBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zoomBoxKeyPressed
         if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        dd.zoom = Float.parseFloat(zoomBox.getText());
        dd.repaint();
        }
    }//GEN-LAST:event_zoomBoxKeyPressed

    private void showPartnersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showPartnersKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        dd.showPartners = showPartners.getText().split(",");
        dd.repaint();
        }
    }//GEN-LAST:event_showPartnersKeyPressed

    private void electricalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_electricalItemStateChanged
        if (electrical.isSelected()){
            dd.showElectrical = 1;
        }else{
            dd.showElectrical = 0;
        }
        dd.repaint();
    }//GEN-LAST:event_electricalItemStateChanged

    private void inItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inItemStateChanged
       if (in.isSelected()){
            dd.showIn = 1;
        }else{
            dd.showIn = 0;
        }
        dd.repaint();
    }//GEN-LAST:event_inItemStateChanged

    private void outItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_outItemStateChanged
        if (out.isSelected()){
            dd.showOut = 1;
        }else{
            dd.showOut = 0;
        }
        dd.repaint();
    }//GEN-LAST:event_outItemStateChanged

    private void backboneItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_backboneItemStateChanged
        if (backbone.isSelected()){
            dd.showBackbone = 1;
        }else{
            dd.showBackbone = 0;
        }
        dd.repaint();
    }//GEN-LAST:event_backboneItemStateChanged
    private static String now() {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy_MM_dd_HH_mm_ss");
        return sdf.format(cal.getTime());

    }



     private void savePNG(New2D d) {
       Dimension size = d.getSize();
       BufferedImage myImage = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);
       //String filePath = "." + File.separator + "images" + File.separator + d.continName + "X" + d.zoom + "_" + d.dtype + "_" + now() + ".png";
       String filePath = d.continName + "X" + d.zoom + "_" + d.dtype + "_" + now() + ".png";
       File imgFile = new File(filePath);
       Graphics2D g2 = myImage.createGraphics();
       d.paint(g2);
       try {
         OutputStream out = new FileOutputStream(imgFile);
         ImageIO.write(myImage, "png", out);

         out.close();
       } catch (Exception e) {
         System.out.println(e);
       }
     }

      public void savePNG(TwoDJFrame f) {
       Dimension size = f.getSize();
       BufferedImage myImage = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_RGB);
       String filePath = now() + ".png";
       File imgFile = new File(filePath);
       Graphics2D g2 = myImage.createGraphics();
       f.paint(g2);
       try {
         OutputStream out = new FileOutputStream(imgFile);
         ImageIO.write(myImage, "png", out);

         out.close();
       } catch (Exception e) {
         System.out.println(e);
       }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox backbone;
    private javax.swing.JCheckBox electrical;
    private javax.swing.JCheckBox in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox out;
    private javax.swing.JButton print;
    private javax.swing.JButton save;
    private javax.swing.JTextPane showPartners;
    private javax.swing.JRadioButton side;
    private javax.swing.JRadioButton top;
    private javax.swing.ButtonGroup viewGroup;
    private javax.swing.JTextField zoomBox;
    private javax.swing.JTextField zspacingBox;
    // End of variables declaration//GEN-END:variables

}